# 📌 Instructions for NumPy and Pandas Hands-on Exercises

1. **All challenges or Tasks are compulsory.**  
   You must complete all the NumPy and Pandas exercises. Do not skip any challenge.

2. **Write your own Python code.**  
   Use the concepts and functions taught in the class to solve each problem.

3. **Run every code cell.**  
   Make sure your code executes successfully and the required output is visible.

4. **Do not hard-code answers.**  
   Your program should calculate the answer. For example, do not manually write the name of the top-performing student. Use NumPy/Pandas to find it.

5. **Use the concepts taught in class.**  
   Try to solve the problems using NumPy arrays, indexing, slicing, array operations, Boolean filtering, Pandas DataFrames, column selection, filtering, sorting, and other concepts discussed in the sessions.

6. **Understand your code.**  
   You should be able to explain what your code does and why you used a particular function or operation.

7. **Do not copy-paste solutions from others.**  
   You may refer to examples discussed in class, but solve the exercises independently.

8. **Check your output carefully.**  
   If the output looks incorrect, check your code and try to identify and fix the problem.



09. **Before submitting, make sure that:**
    - All NumPy challenges are completed.
    - All Pandas challenges are completed.
    - All code cells have been executed.
    - Required outputs are visible.
    - There are no unresolved errors.
    - You can explain your solutions.

11. **Save and Submit Your Notebook.**  
    Save your notebook file using your **Roll Number** as the filename.  
    For example: `AIDE2026_001.ipynb`

    After completing the exercises, **submit the notebook file on Google Classroom**.

### 🎯 Objective

The objective of these exercises is **not only to get the correct output**, but to learn how to use **NumPy and Pandas to solve real-world data problems using Python.**

# Real life Problem
## Suppose we have a marks of 10 students. We want to perform the following operation
* Calculate the average
* Add 5 marks to everyone, find the highest mark
* Find how many students scored above 50

In [6]:
marks=[45, 67, 32, 89,56, 72, 41, 90, 63, 55]

### How would you calculate the average?

In [7]:
sum(marks)/len(marks)

61.0

## Challenges
* Don't you think that this is little complicated
* To overcome this, numpy has been introduced.

In [8]:
import numpy as np
marks=np.array([marks])

# 2. Activity 1- Creating Numpy Arrays

In [9]:
import numpy as np
a=np.array([10,20,30,40,50])

print(a)
print(type(a))

[10 20 30 40 50]
<class 'numpy.ndarray'>

In [10]:
print(a.shape)
print(a.ndim)
print(a.size)
print(a.dtype)

(5,)
1
5
int64

# 3. Activity 2- Numpy vs Python List

In [15]:
marks=[40,50,60,70]

In [16]:
marks+5

TypeError: can only concatenate list (not "int") to list

In [18]:
marks=np.array([40,50,60,70])
print(marks+5)

[45 55 65 75]

### Numpy allows us to perform the same mathematical operations on the entire array

# Activity 3- Basic Mathematical Operations

In [19]:
prices=np.array([100,200,300,400,500])

**Add Rs 50**

In [20]:
prices+50

array([150, 250, 350, 450, 550])

**10% Discount**

In [21]:
prices*.90

array([ 90., 180., 270., 360., 450.])

**Double the price**

In [22]:
prices*2

array([ 200,  400,  600,  800, 1000])

**Divide by 2**

In [23]:
prices/2

array([ 50., 100., 150., 200., 250.])

**Square**

In [24]:
prices**2

array([ 10000,  40000,  90000, 160000, 250000])

# Activity 4- Important Statistical Functions

In [25]:
marks=np.array([45,67,32,89,56,72,41,90,63,55])

**Average**

In [26]:
print(marks.mean())

61.0

**Maximum**

In [27]:
print(marks.max())

90

**Minimum**

In [28]:
print(marks.min())

32

**Total**

In [29]:
print(marks.sum())

610

**Standard Deviation**

In [30]:
print(marks.std())

18.286607121059937

**Median**

In [31]:
print(np.median(marks)) #alternate method of writing

59.5

**Find the difference between the highest and lowest marks**

In [32]:
a=np.min(marks)-np.max(marks)
print(-a)
print("aliter")
b=marks.max()-marks.min()
print(b)

58
aliter
58

# Activity 5- Indexing and Slicing

In [33]:
marks=np.array([45,67,32,89,56,72,41,90,63,55])

# IDK why yaha inka output like a datatype aya hai , on using print function ahead of each we get normal ans

**What is the first mark?**

In [34]:
marks[0]

np.int64(45)

**What is the last mark?**

In [35]:
print(marks[-1])

55

**First three marks?**

In [36]:
marks[:3] # agar print function ke ander dalo toh list print hoga, aise array likhke nhi ayega

array([45, 67, 32])

**Marks from position 3 to 6?**

In [37]:
marks[3:7] #last wala i.e 7 is exclusive

array([89, 56, 72, 41])

**Every second mark?**

In [38]:
print(marks[::2])

[45 32 56 41 63]

lets try

In [39]:
a=marks[::3]
print(a)
print(type(a))#so inka output array hi hai , therefor we can perform furthur functions

[45 89 41 55]
<class 'numpy.ndarray'>

# Activity 6-Boolean Filtering

In [40]:
marks=np.array([45,67,32,89,56,72,41,90,90,63,55])

**Which students scored more than 60?***

In [41]:
marks>60

array([False,  True, False,  True, False,  True, False,  True,  True,
        True, False])

In [42]:
#self
print(marks>60)
print(type(marks>60))

[False  True False  True False  True False  True  True  True False]
<class 'numpy.ndarray'>

In [43]:
marks[marks>60]

array([67, 89, 72, 90, 90, 63])

In [44]:
#self
print(marks[marks>60])

[67 89 72 90 90 63]

In [45]:
#self
print(marks[not(marks>60)]) # to understand, ask copilot

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [47]:
#self
print(marks[~(marks > 60)])          # using ~
print(marks[np.logical_not(marks > 60)])  # using logical_not
# not wala operator is a scalar not a vector, not sirf tabh hi work karta hai jab single true ya false value ho, na ki puri array

[45 32 56 41 55]
[45 32 56 41 55]

# Activity 7-2D Arrays

In [48]:
marks=np.array([
    [80,70,89],
    [20,40,90],
    [30,48,89],
    [55,89,58]
])

In [49]:
print(marks.shape)

(4, 3)

**First subjects's marks?**

In [50]:
marks[:,0]

array([80, 20, 30, 55])

**Fist students marks**

In [51]:
print(marks[0,:])

[80 70 89]

**first student first subject marks**

In [52]:
print(marks[0,0])

80

# Activity 8- Row and Column Calculations

In [53]:
marks.mean(axis=0) #collapses rows

array([46.25, 61.75, 81.5 ])

In [54]:
marks.mean(axis=1) #collapses columns

array([79.66666667, 50.        , 55.66666667, 67.33333333])

# Mini-Project-1 Student Marks Analyzer

## Dataset

In [55]:
import numpy as np

In [56]:
import numpy as np

marks = np.array([
    [78, 85, 90],
    [65, 70, 72],
    [88, 92, 95],
    [55, 60, 58],
    [92, 89, 94]
])

Assume:
* Each row represents one student
* Columns represent Python, Maths, and AI, respectively
* Each subject is out of 100

## Task 1: Task 1 — Understand the Dataset
Find
* Number of students
* Number of subjects
* Total number of marks

In [57]:
print(marks.shape)
a=marks.shape #remeber no brackets , tuple is not callable dikhayega (tuple aisa function nhi jise call kar sake)
print("no.of stu",a[0]) #shape is similar to lenght so no jhunjat of doing +1
print(marks.size)

(5, 3)
no.of stu 5
15

## Task 2: Subject-wise Analysis
Find the average marks in each subject.
Your output should tell you:
* Average Python marks:?
* Average Maths marks:?
* Average AI marks:?

In [58]:
print("average python",marks.mean(axis=0)[0])#axis =0 collapses rows
print(marks.mean(axis=0))#sare subjects ka avg print milega

average python 75.6
[75.6 79.2 81.8]

# Task 3: Student-wise Analysis
Find the average marks of every student.
Expected output:
* student 1:?
* student 2:?
* Student 3:?
* Student 4:?
* Student 5:?

In [59]:
print("student 1",marks.mean(axis=1)[0])
#of all respectively :
print(marks.mean(axis=1))

student 1 84.33333333333333
[84.33333333 69.         91.66666667 57.66666667 91.66666667]

# Task 4: Find the Top Performer
Find the student who has the highest average marks.
Also find the student's average

In [60]:
a=marks.mean(axis=1)
print("highest marks:",a.max())
i=0
while i < a.size:
    if a[i]==a.max():
        s=i
    i+=1
print("the highest scorer is:","student",s)

highest marks: 91.66666666666667
the highest scorer is: student 4

# Task 5: Find the Weakest Performer
Find the student who has the lowest average marks.

Also find the student's average

In [61]:
# same just use min

# Task 6: Students Who Performed Well
Find all students whose marks are greater than 75.
Don't manually check each student.
* Use Boolean filtering

In [62]:
a = marks.mean(axis=1)          # average per student
good_students = np.where(a > 75)[0]   # indices of students with avg > 75 # obswerve [0] after np.where
print("Students with average > 75:", good_students)
print("Their averages:", a[good_students])

Students with average > 75: [0 2 4]
Their averages: [84.33333333 91.66666667 91.66666667]

# SELF

### Why `np.where(a > 75)[0]` is used

- `np.where(condition)` returns a **tuple of arrays**, one for each dimension of the input.
- Since `a` is a **1D array** (student averages), the result looks like:
  ```python
  (array([0, 2, 4]),)

### Understanding `numpy.where()`

`numpy.where()` is a powerful function used for **conditional selection** in arrays.

---

#### 1. Basic Usage
```python
np.where(condition) returns all the values in array that satisfy the condition

better to see official doc, (hover over it)

# Task 7: Subject-wise Highest Marks.
Find the highest mark obtained in :
* Python
* Maths
* AI

In [63]:
c=marks[:,1] #extracting maths column
print(c.max())

92

# Task 8: Add Grace Marks

The Institute gives 5 grace marks to every student in every subject.

Create a new Numpy array containing the upldated marks.

* Important: Do not modify the original marks array

In [64]:
updated_marks=marks + 5
print(updated_marks)

[[ 83  90  95]
 [ 70  75  77]
 [ 93  97 100]
 [ 60  65  63]
 [ 97  94  99]]

# Task 9: Apply a Condition
Suppose grace marks connot make a student's marks exceed 100.
Create an updated marks array where:
* if marks+5>100, keep th mark as 100.
* Otherwise, add5

In [65]:
updated_marks=marks+5
k=np.where(updated_marks>100,100,updated_marks)
print(k)

[[ 83  90  95]
 [ 70  75  77]
 [ 93  97 100]
 [ 60  65  63]
 [ 97  94  99]]

# Task 10: Pass/Fail Analysis
A student is considered passed if their average marks are 60 or above.

Find:
* Average marks of every student
* Which students passed
* Which students failed
* Number of students who passed
* Number of students who failed
# self:this is a good question

In [66]:
a= marks.mean(axis=1)
passed=a>=60
failed=a<60
print("passed students",np.where(passed)[0])

print("no.of passed",np.where(passed)[0].size)

passed students [0 1 2 4]
no.of passed 4

# Task 11: Subject Perforamnce
Find which subject has the highest average marks
Your program should output something like:
* Best performing student :AI
* Average marks:81.8

In [67]:
a=marks.mean(axis=0)
b=a.max()
c=np.where(a==b)[0]
lis=["ai","python","maths"]
i=0
while i<10:
    if c==i:
        d=lis[i]
        break
    i+=1
        
print("the subjext that has highest average marks is",d)

the subjext that has highest average marks is maths

# Task 12: Challenge
Find students who satisfy both conditions
* Average marks>75
* And AI marks>90

This forces students to combine two Boolean conditions.

In [68]:
a=marks.mean(axis=1)
b=marks[:,2]
print(np.where((a>75) & (b>90))[0])
#numpy me & for and

[2 4]

# Task 13: Challenge
Calculate the percentage of every student.
Since there are 3 subjects and each is out of 100:
* Total Maximum marks=300

For exampel:
* Percentage=Total marks/300*100

In [69]:
# simple

# Task 14 — Final Challenge 
Create a performance report using NumPy.
For each student, determine:
* Student 1 → Excellent / Good / Needs Improvement

Use these rules:

* Average	Performance
* ≥ 85	Excellent
* ≥ 70 and < 85	Good
* < 70	Needs Improvement

Do not manually assign the labels. Use NumPy conditions.

In [70]:
a=marks.mean(axis=1)

for i in range(0,a.size):
    if a[i] >=85:
        print("student",i,"excellent")
    elif a[i] >= 70:
        print("student",i,"good")
    else:
        print("student",i,"needs improvement")

student 0 good
student 1 needs improvement
student 2 excellent
student 3 needs improvement
student 4 excellent

# Real-Life Problem
## Suppose we give you  marks of 10 students in an excel file. How you can quickly find the average, highest scorer, students who failed, and subject-wise perforance?


| Name  | Python | Maths | AI |
| ----- | -----: | ----: | -: |
| Aman  |     78 |    85 | 90 |
| Priya |     65 |    70 | 72 |
| Rahul |     88 |    92 | 95 |
| Neha  |     55 |    60 | 58 |
| Arjun |     92 |    89 | 94 |

**Pandas allows Python to work with data like an excel table**

## 2. Import Pandas

In [71]:
%pip install pandas

Requirement already satisfied: pandas in c:\Users\Soham Gupta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Soham Gupta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Soham Gupta\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Soham Gupta\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.5 in C:\Users\Soham Gupta\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [72]:
import pandas as pd

# 3. Create our first DataFrame

In [73]:
data={
    "Name":["Aman", "Priya", "Rahul", "Neha", "Arjun"],
    "Python":[78,65,88,55,92],
    "Maths":[85,70,92,60,89],
    "AI":[90,72,95,58,94]
}

df=pd.DataFrame(data)

print(df)

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**DataFrame= A Table in Python**

# 4. Understanding the DataFrame

**see the first few rows**

In [74]:
df.head()# first 5 row dikhata hai , inke data me 5 hi thi so.....

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**see the last few rows**

In [75]:
df.tail() #last 5 row but in gareebo ke pass 5 hi thi

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94

**Number of rows and columns**

In [76]:
df.shape #note that index wali is not included

(5, 4)

**Column names**

**Data Types**

In [77]:
df.dtypes

Name        str
Python    int64
Maths     int64
AI        int64
dtype: object

**Basic Information**

In [78]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Python  5 non-null      int64
 2   Maths   5 non-null      int64
 3   AI      5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 292.0 bytes

In [79]:
print(df.info)
print(type(df))

<bound method DataFrame.info of     Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95
3   Neha      55     60  58
4  Arjun      92     89  94>
<class 'pandas.DataFrame'>

# Selecting a column

**Single Column**

In [80]:
df["Python"]

0    78
1    65
2    88
3    55
4    92
Name: Python, dtype: int64

**Multiple Column**

In [81]:
df[["AI","Python"]]

   AI  Python
0  90      78
1  72      65
2  95      88
3  58      55
4  94      92

In [82]:
#self
pd.DataFrame(data)[["Python","AI"]]

   Python  AI
0      78  90
1      65  72
2      88  95
3      55  58
4      92  94

### Import Concept
**One pair of brackets==> one column**

**Double Brackets==>multiple columns**

# Selecting Rows

In [83]:
df.iloc[0]

Name      Aman
Python      78
Maths       85
AI          90
Name: 0, dtype: object

**iloc means select using position**

**First Row**

In [84]:
print(df.iloc[0])

Name      Aman
Python      78
Maths       85
AI          90
Name: 0, dtype: object

**Second Row**

In [85]:
df.iloc[1]

Name      Priya
Python       65
Maths        70
AI           72
Name: 1, dtype: object

**First three Rows**

In [86]:
df.iloc[0:3]

    Name  Python  Maths  AI
0   Aman      78     85  90
1  Priya      65     70  72
2  Rahul      88     92  95

# 7. Filtering -The most important Part

**"Show me students who scored more than 80 in Python"**

In [87]:
df[df["Python"]>80]

    Name  Python  Maths  AI
2  Rahul      88     92  95
4  Arjun      92     89  94

In [88]:
#self
print(df["Python"]>80)


# isliye upper df[df["Python"]>80] kiya hai

0    False
1    False
2     True
3    False
4     True
Name: Python, dtype: bool

# 8. Multiple Conditions

**"Who scored more than 80 in python and maths?"**

In [89]:
df[(df["Python"]>80)& (df["Maths"]>80)]

    Name  Python  Maths  AI
2  Rahul      88     92  95
4  Arjun      92     89  94

In [90]:
df[(df["Python"]>80)| (df["Maths"]>80)] # | is or in numpy operations

    Name  Python  Maths  AI
0   Aman      78     85  90
2  Rahul      88     92  95
4  Arjun      92     89  94

# 9. Creating a New Column

In [91]:
df["Total"]=df["Python"]+df["Maths"]+df["AI"]

In [92]:
print(df)

    Name  Python  Maths  AI  Total
0   Aman      78     85  90    253
1  Priya      65     70  72    207
2  Rahul      88     92  95    275
3   Neha      55     60  58    173
4  Arjun      92     89  94    275

In [93]:
df["Percentage"]=df["Total"]/3

In [94]:
df

    Name  Python  Maths  AI  Total  Percentage
0   Aman      78     85  90    253   84.333333
1  Priya      65     70  72    207   69.000000
2  Rahul      88     92  95    275   91.666667
3   Neha      55     60  58    173   57.666667
4  Arjun      92     89  94    275   91.666667

# 11. Basic Statistics

**Average Python Marks**

In [95]:
df["Python"].mean()

np.float64(75.6)

**Highest**

In [96]:
df["Python"].max()

np.int64(92)

In [97]:
print(df["Python"].max())

92

**Lowest**

In [98]:
df["Python"].min()

np.int64(55)

**Total**

In [99]:
df["Python"].sum()

np.int64(378)

**Count**

In [100]:
df["Python"].count()

np.int64(5)

**Complete Numerical Summary-Describe()**

In [101]:
df.describe()

          Python      Maths        AI       Total  Percentage
count   5.000000   5.000000   5.00000    5.000000    5.000000
mean   75.600000  79.200000  81.80000  236.600000   78.866667
std    15.533834  13.663821  16.22344   45.108757   15.036252
min    55.000000  60.000000  58.00000  173.000000   57.666667
25%    65.000000  70.000000  72.00000  207.000000   69.000000
50%    78.000000  85.000000  90.00000  253.000000   84.333333
75%    88.000000  89.000000  94.00000  275.000000   91.666667
max    92.000000  92.000000  95.00000  275.000000   91.666667

In [102]:
#self
print(df)

    Name  Python  Maths  AI  Total  Percentage
0   Aman      78     85  90    253   84.333333
1  Priya      65     70  72    207   69.000000
2  Rahul      88     92  95    275   91.666667
3   Neha      55     60  58    173   57.666667
4  Arjun      92     89  94    275   91.666667

In [103]:
#self
print(df.describe())

          Python      Maths        AI       Total  Percentage
count   5.000000   5.000000   5.00000    5.000000    5.000000
mean   75.600000  79.200000  81.80000  236.600000   78.866667
std    15.533834  13.663821  16.22344   45.108757   15.036252
min    55.000000  60.000000  58.00000  173.000000   57.666667
25%    65.000000  70.000000  72.00000  207.000000   69.000000
50%    78.000000  85.000000  90.00000  253.000000   84.333333
75%    88.000000  89.000000  94.00000  275.000000   91.666667
max    92.000000  92.000000  95.00000  275.000000   91.666667

# 11 Missing Values

In [104]:
data={
    " Name":["Aman","Priya","Rahul","Neha", "Arjun"],
    "Python":[78,65,88,None,92],
    "Math":[85,70,92,60,89],
    "AI":[90,72,95,58,94]
}
df=pd.DataFrame(data)

In [105]:
df.isnull()

    Name  Python   Math     AI
0  False   False  False  False
1  False   False  False  False
2  False   False  False  False
3  False    True  False  False
4  False   False  False  False

In [106]:
#self
print(df==(None)) 

# search the reason on google.

    Name  Python   Math     AI
0  False   False  False  False
1  False   False  False  False
2  False   False  False  False
3  False   False  False  False
4  False   False  False  False

In [107]:
df.isnull().sum()

 Name     0
Python    1
Math      0
AI        0
dtype: int64

#  12. Handling Missing Values

**Remove rows containing missing values**

In [108]:
df.dropna()

    Name  Python  Math  AI
0   Aman    78.0    85  90
1  Priya    65.0    70  72
2  Rahul    88.0    92  95
4  Arjun    92.0    89  94

**Or fill the missing values**

In [109]:
df["Python"]=df["Python"].fillna(df["Python"].mean())

In [110]:
df

    Name  Python  Math  AI
0   Aman   78.00    85  90
1  Priya   65.00    70  72
2  Rahul   88.00    92  95
3   Neha   80.75    60  58
4  Arjun   92.00    89  94

### Instead of simply deleting the student, we can replace the missing mark with a reasonable value such as the average

# 13. Reading a Real CSV File

**Now move from manually created data to the real dataset**

inlogo ne nhi di abc.csv

In [111]:
#self abc.csv generated using ai
import csv

data = [
    [1,"Soham",18,"Ropar","soham@example.com","Python Basics",85,"2026-07-27"],
    [2,"Ananya",20,"Delhi","ananya@example.com","Data Science",90,"2026-07-28"],
    [3,"Rahul",19,"Mumbai","rahul@example.com","Robotics",78,"2026-07-29"],
    [4,"Meera",21,"Bangalore","meera@example.com","AI Fundamentals",92,"2026-07-30"],
    [5,"Arjun",22,"Chennai","arjun@example.com","Web Development",88,"2026-07-31"],
    [6,"Kavya",20,"Pune","kavya@example.com","CAD Design",81,"2026-08-01"],
    [7,"Rohan",23,"Kolkata","rohan@example.com","Git & Version Control",76,"2026-08-02"],
    [8,"Neha",19,"Hyderabad","neha@example.com","Machine Learning",95,"2026-08-03"],
    [9,"Dev",21,"Jaipur","dev@example.com","Arduino Robotics",83,"2026-08-04"],
    [10,"Ishita",22,"Ahmedabad","ishita@example.com","Startup Basics",89,"2026-08-05"]
]

header = ["ID","Name","Age","City","Email","Course","Score","Joined"]

with open("abc.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(header)
    writer.writerows(data)

print("abc.csv created successfully!")

abc.csv created successfully!

In [112]:
df=pd.read_csv("abc.csv")

In [113]:
df

,ID,Name,Age,City,Email,Course,Score,Joined
0,1,Soham,18,Ropar,soham@example.com,Python Basics,85,2026-07-27
1,2,Ananya,20,Delhi,ananya@example.com,Data Science,90,2026-07-28
2,3,Rahul,19,Mumbai,rahul@example.com,Robotics,78,2026-07-29
3,4,Meera,21,Bangalore,meera@example.com,AI Fundamentals,92,2026-07-30
4,5,Arjun,22,Chennai,arjun@example.com,Web Development,88,2026-07-31
5,6,Kavya,20,Pune,kavya@example.com,CAD Design,81,2026-08-01
6,7,Rohan,23,Kolkata,rohan@example.com,Git & Version Control,76,2026-08-02
7,8,Neha,19,Hyderabad,neha@example.com,Machine Learning,95,2026-08-03
8,9,Dev,21,Jaipur,dev@example.com,Arduino Robotics,83,2026-08-04
9,10,Ishita,22,Ahmedabad,ishita@example.com,Startup Basics,89,2026-08-05

In [114]:
df.head()

,ID,Name,Age,City,Email,Course,Score,Joined
0,1,Soham,18,Ropar,soham@example.com,Python Basics,85,2026-07-27
1,2,Ananya,20,Delhi,ananya@example.com,Data Science,90,2026-07-28
2,3,Rahul,19,Mumbai,rahul@example.com,Robotics,78,2026-07-29
3,4,Meera,21,Bangalore,meera@example.com,AI Fundamentals,92,2026-07-30
4,5,Arjun,22,Chennai,arjun@example.com,Web Development,88,2026-07-31

# Mini Project — Student Performance Analyzer

In [115]:
import pandas as pd

data = {
    "Name": ["Aman", "Priya", "Rahul", "Neha", "Arjun",
             "Simran", "Karan", "Meena"],
    "Python": [78, 65, 88, 55, 92, 74, 61, 85],
    "Maths": [85, 70, 92, 60, 89, 80, 67, 90],
    "AI": [90, 72, 95, 58, 94, 82, 70, 88]
}

df = pd.DataFrame(data)

# Part A — Understanding the Data

## Challenge 1 — Explore the Dataset
Find:
* Number of students
* Number of subjects
* Column names
* Data types of each column

Hint: Think about shape, columns, and dtypes.

In [116]:
print(df.shape)#student,subjects+1
print(df.iloc[0]) #column names is row 0
print(df.dtypes)

(8, 4)
Name      Aman
Python      78
Maths       85
AI          90
Name: 0, dtype: object
Name        str
Python    int64
Maths     int64
AI        int64
dtype: object

## Challenge 2 — Display Students
Display:
* First 5 students
* Last 3 students

Hint: head() and tail()

In [ ]:
print(df.iloc[0:5]) #remember 5 is exclusive
print(df.tail(3))

    Name  Python  Maths  AI  Total    average
0   Aman      78     85  90    253  84.333333
1  Priya      65     70  72    207  69.000000
2  Rahul      88     92  95    275  91.666667
3   Neha      55     60  58    173  57.666667
4  Arjun      92     89  94    275  91.666667
     Name  Python  Maths  AI  Total    average
5  Simran      74     80  82    236  78.666667
6   Karan      61     67  70    198  66.000000
7   Meena      85     90  88    263  87.666667

## Challenge 3 — Select Columns
Display only:
* Student names
* Python marks
* Name and AI marks
* Name, Maths, and AI marks

In [ ]:
df[["Name","AI"]] #print() use karoge toh output not proper

     Name  AI
0    Aman  90
1   Priya  72
2   Rahul  95
3    Neha  58
4   Arjun  94
5  Simran  82
6   Karan  70
7   Meena  88

# Part B — Basic Analysis
## Challenge 4 — Python Performance
Find:
* Average Python marks
* Highest Python marks
* Lowest Python marks
* Total Python marks

In [119]:
print(df["Python"].mean())
#and so on

74.75

## Challenge 5 — Subject-wise Analysis
Find the average marks of all three subjects.

Your output should clearly indicate:

* Python: ?
* Maths: ?
* AI: ?

In [120]:
#done

## Challenge 6 — Find the Top Performer in a Subject
Find:
* Student with the highest Python marks
* Student with the highest Maths marks
* Student with the highest AI marks

Think: You need both the name and the marks.

In [121]:
print(df.loc[df["Python"]==df["Python"].max()])

    Name  Python  Maths  AI
4  Arjun      92     89  94

In [133]:
#see print se improper output
df.loc[df["Python"]==df["Python"].max()]

    Name  Python  Maths  AI  Total    average
4  Arjun      92     89  94    275  91.666667

# Part C — Creating New Information

## Challenge 7 — Total Marks
Create a new column called:
* Total

It should contain the total marks obtained by each student in all three subjects.

In [122]:
df["Total"]=df["Python"]+df["AI"]+df["Maths"]
print(df)

     Name  Python  Maths  AI  Total
0    Aman      78     85  90    253
1   Priya      65     70  72    207
2   Rahul      88     92  95    275
3    Neha      55     60  58    173
4   Arjun      92     89  94    275
5  Simran      74     80  82    236
6   Karan      61     67  70    198
7   Meena      85     90  88    263

## Challenge 8 — Percentage
Create a new column called:
* Percentage

Assume each subject is out of 100.

In [123]:
#total/3

## Challenge 9 — Average Marks
Create another column:
* Average

It should contain the average marks of each student.

In [124]:
#same

# Part D — Filtering

## Challenge 11 — High Performers
Display students who scored more than 80 in AI.

In [125]:
print(df.loc[df["AI"]>80])

     Name  Python  Maths  AI  Total
0    Aman      78     85  90    253
2   Rahul      88     92  95    275
4   Arjun      92     89  94    275
5  Simran      74     80  82    236
7   Meena      85     90  88    263

## Challenge 12 — Multiple Conditions
Display students who:
* scored more than 80 in Python AND more than 80 in Maths.

In [126]:
a=df["Python"]>80
b=df["Maths"]>80
c=a & b
print(c)
print(df.loc[c])

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7     True
dtype: bool
    Name  Python  Maths  AI  Total
2  Rahul      88     92  95    275
4  Arjun      92     89  94    275
7  Meena      85     90  88    263

## Challenge 13 — Find Good Students
Display students whose:
* Average ≥ 70

In [127]:

print(df.loc[df["Total"]>=210])
print("aliter")
df["average"]= df["Total"]/3

     Name  Python  Maths  AI  Total
0    Aman      78     85  90    253
2   Rahul      88     92  95    275
4   Arjun      92     89  94    275
5  Simran      74     80  82    236
7   Meena      85     90  88    263
aliter

## Challenge 14 — Find Students Needing Improvement
Display students whose:
* Average < 60

In [128]:
#same just ,60

## Challenge 15 — Subject Combination 
Find students who satisfy both:
* Python marks ≥ 80
* AND AI marks ≥ 90

In [129]:
#same as 12

# Part F — Final Challenge

## Challenge 16 — Complete Student Report
Create a final DataFrame containing:

* Name
* Python
* Maths
* AI
* Total
* Percentage
* Average
* Performance

The :
* 1. Sort students from highest to lowest percentage.
* 2. Display the top 3 students.
* 3. Display students who need improvement.
* 4. Find the class average percentage.
* 5. Find the highest percentage.
* 6. Find the lowest percentage.